# Generated by Django 5.1.15 on 2026-08-19 20:14

from django.db import migrations, models


def create_faq_table_if_missing(apps, schema_editor):
    table_name = "accounts_faqentry"
    existing_tables = schema_editor.connection.introspection.table_names()
    if table_name not in existing_tables:
        schema_editor.create_model(apps.get_model("accounts", "FAQEntry"))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(create_faq_table_if_missing, migrations.RunPython.noop)],
            state_operations=[migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Ex: Pare-feu, Phishing, VPN', max_length=200)),
                ('mots_cles', models.CharField(help_text='Mots séparés par des virgules, utilisés pour la recherche (ex: pare-feu, firewall, protection réseau)', max_length=300)),
                ('reponse', models.TextField()),
            ],
            )],
        ),
    ]
