# Generated by Django 5.1.15 on 2026-08-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationseuils',
            name='seuil_critique',
        ),
        migrations.RemoveField(
            model_name='configurationseuils',
            name='seuil_intermediaire',
        ),
        migrations.AddField(
            model_name='configurationseuils',
            name='seuil_niveau2',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='configurationseuils',
            name='seuil_niveau3',
            field=models.PositiveIntegerField(default=47),
        ),
        migrations.AddField(
            model_name='configurationseuils',
            name='seuil_niveau4',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='configurationseuils',
            name='seuil_niveau5',
            field=models.PositiveIntegerField(default=93),
        ),
    ]
