# Generated by Django 5.1.15 on 2026-08-26 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_configurationseuils_seuil_critique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAccompagnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
                ('reponse', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('EN_COURS', 'En cours'), ('RESOLUE', 'Résolue')], default='NOUVELLE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_accompagnement', to=settings.AUTH_USER_MODEL)),
                ('pme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_accompagnement', to='accounts.pme')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
