# Generated by Django 5.1.15 on 2026-09-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_faq_and_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeaccompagnement',
            name='statut',
            field=models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('EN_COURS', 'En cours'), ('RESOLUE', 'Résolue'), ('REFUSEE', 'Refusée')], default='NOUVELLE', max_length=20),
        ),
    ]
