# Generated by Django 5.1.15 on 2026-09-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
        ('accounts', '0007_merge_faq_and_profile'),
    ]

    operations = [
    ]
