# Generated by Django 5.1.15 on 2026-09-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_demandeaccompagnement_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profils/'),
        ),
    ]
