# Generated by Django 5.1.15 on 2026-09-11 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_photo_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeSuivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('reponse', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_suivi_recues', to=settings.AUTH_USER_MODEL)),
                ('pme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_suivi', to='accounts.pme')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
