# Generated by Django 5.1.15 on 2026-08-15 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_configurationseuils_seuil_critique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('texte', models.TextField()),
                ('ref_iso27001', models.CharField(blank=True, max_length=50)),
                ('ref_nist', models.CharField(blank=True, max_length=50)),
                ('ref_loi0908', models.CharField(blank=True, max_length=50)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Referentiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('score_maximum', models.PositiveIntegerField(default=116)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChoixReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.PositiveSmallIntegerField()),
                ('libelle_niveau', models.CharField(max_length=50)),
                ('texte', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='referentiel.question')),
            ],
            options={
                'ordering': ['valeur'],
                'unique_together': {('question', 'valeur')},
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée')], default='EN_COURS', max_length=20)),
                ('score_total', models.PositiveIntegerField(blank=True, null=True)),
                ('pme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='accounts.pme')),
                ('referentiel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='referentiel.referentiel')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('referentiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='referentiel.referentiel')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='referentiel.theme'),
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
                ('choix', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reponses', to='referentiel.choixreponse')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='referentiel.evaluation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='referentiel.question')),
            ],
            options={
                'unique_together': {('evaluation', 'question')},
            },
        ),
    ]
