# Generated by Django 5.1.15 on 2026-08-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='recommandation',
            field=models.TextField(blank=True),
        ),
    ]
